FROM node:22-bookworm-slim

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --prod=false --config.only-built-dependencies=esbuild

COPY . .

CMD ["pnpm", "worker:optimization"]
